/*
 * This file is generated by jOOQ.
 */
package com.rc.db.tables.records;


import com.rc.db.tables.Notifications;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> implements Record12<Long, String, String, String, String, String, Integer, LocalDateTime, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1521455416;

    /**
     * Setter for <code>notifications.id</code>.
     */
    public NotificationsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notifications.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notifications.target_url</code>.
     */
    public NotificationsRecord setTargetUrl(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>notifications.target_url</code>.
     */
    public String getTargetUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notifications.method</code>.
     */
    public NotificationsRecord setMethod(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>notifications.method</code>.
     */
    public String getMethod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notifications.headers</code>.
     */
    public NotificationsRecord setHeaders(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>notifications.headers</code>.
     */
    public String getHeaders() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notifications.body</code>.
     */
    public NotificationsRecord setBody(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>notifications.body</code>.
     */
    public String getBody() {
        return (String) get(4);
    }

    /**
     * Setter for <code>notifications.status</code>.
     */
    public NotificationsRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>notifications.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>notifications.attempts</code>.
     */
    public NotificationsRecord setAttempts(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>notifications.attempts</code>.
     */
    public Integer getAttempts() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>notifications.next_retry_at</code>.
     */
    public NotificationsRecord setNextRetryAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>notifications.next_retry_at</code>.
     */
    public LocalDateTime getNextRetryAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>notifications.last_error</code>.
     */
    public NotificationsRecord setLastError(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>notifications.last_error</code>.
     */
    public String getLastError() {
        return (String) get(8);
    }

    /**
     * Setter for <code>notifications.idempotency_key</code>.
     */
    public NotificationsRecord setIdempotencyKey(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>notifications.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(9);
    }

    /**
     * Setter for <code>notifications.created_at</code>.
     */
    public NotificationsRecord setCreatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>notifications.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>notifications.updated_at</code>.
     */
    public NotificationsRecord setUpdatedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>notifications.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, Integer, LocalDateTime, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, String, Integer, LocalDateTime, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notifications.NOTIFICATIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return Notifications.NOTIFICATIONS.TARGET_URL;
    }

    @Override
    public Field<String> field3() {
        return Notifications.NOTIFICATIONS.METHOD;
    }

    @Override
    public Field<String> field4() {
        return Notifications.NOTIFICATIONS.HEADERS;
    }

    @Override
    public Field<String> field5() {
        return Notifications.NOTIFICATIONS.BODY;
    }

    @Override
    public Field<String> field6() {
        return Notifications.NOTIFICATIONS.STATUS;
    }

    @Override
    public Field<Integer> field7() {
        return Notifications.NOTIFICATIONS.ATTEMPTS;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Notifications.NOTIFICATIONS.NEXT_RETRY_AT;
    }

    @Override
    public Field<String> field9() {
        return Notifications.NOTIFICATIONS.LAST_ERROR;
    }

    @Override
    public Field<String> field10() {
        return Notifications.NOTIFICATIONS.IDEMPOTENCY_KEY;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Notifications.NOTIFICATIONS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Notifications.NOTIFICATIONS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTargetUrl();
    }

    @Override
    public String component3() {
        return getMethod();
    }

    @Override
    public String component4() {
        return getHeaders();
    }

    @Override
    public String component5() {
        return getBody();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public Integer component7() {
        return getAttempts();
    }

    @Override
    public LocalDateTime component8() {
        return getNextRetryAt();
    }

    @Override
    public String component9() {
        return getLastError();
    }

    @Override
    public String component10() {
        return getIdempotencyKey();
    }

    @Override
    public LocalDateTime component11() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTargetUrl();
    }

    @Override
    public String value3() {
        return getMethod();
    }

    @Override
    public String value4() {
        return getHeaders();
    }

    @Override
    public String value5() {
        return getBody();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public Integer value7() {
        return getAttempts();
    }

    @Override
    public LocalDateTime value8() {
        return getNextRetryAt();
    }

    @Override
    public String value9() {
        return getLastError();
    }

    @Override
    public String value10() {
        return getIdempotencyKey();
    }

    @Override
    public LocalDateTime value11() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdatedAt();
    }

    @Override
    public NotificationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationsRecord value2(String value) {
        setTargetUrl(value);
        return this;
    }

    @Override
    public NotificationsRecord value3(String value) {
        setMethod(value);
        return this;
    }

    @Override
    public NotificationsRecord value4(String value) {
        setHeaders(value);
        return this;
    }

    @Override
    public NotificationsRecord value5(String value) {
        setBody(value);
        return this;
    }

    @Override
    public NotificationsRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public NotificationsRecord value7(Integer value) {
        setAttempts(value);
        return this;
    }

    @Override
    public NotificationsRecord value8(LocalDateTime value) {
        setNextRetryAt(value);
        return this;
    }

    @Override
    public NotificationsRecord value9(String value) {
        setLastError(value);
        return this;
    }

    @Override
    public NotificationsRecord value10(String value) {
        setIdempotencyKey(value);
        return this;
    }

    @Override
    public NotificationsRecord value11(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotificationsRecord value12(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public NotificationsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Integer value7, LocalDateTime value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Long id, String targetUrl, String method, String headers, String body, String status, Integer attempts, LocalDateTime nextRetryAt, String lastError, String idempotencyKey, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Notifications.NOTIFICATIONS);

        set(0, id);
        set(1, targetUrl);
        set(2, method);
        set(3, headers);
        set(4, body);
        set(5, status);
        set(6, attempts);
        set(7, nextRetryAt);
        set(8, lastError);
        set(9, idempotencyKey);
        set(10, createdAt);
        set(11, updatedAt);
    }
}
