/*
 * This file is generated by jOOQ.
 */
package com.rc.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notifications implements Serializable {

    private static final long serialVersionUID = -1196019003;

    private Long          id;
    private String        targetUrl;
    private String        method;
    private String        headers;
    private String        body;
    private String        status;
    private Integer       attempts;
    private LocalDateTime nextRetryAt;
    private String        lastError;
    private String        idempotencyKey;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Notifications() {}

    public Notifications(Notifications value) {
        this.id = value.id;
        this.targetUrl = value.targetUrl;
        this.method = value.method;
        this.headers = value.headers;
        this.body = value.body;
        this.status = value.status;
        this.attempts = value.attempts;
        this.nextRetryAt = value.nextRetryAt;
        this.lastError = value.lastError;
        this.idempotencyKey = value.idempotencyKey;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Notifications(
        Long          id,
        String        targetUrl,
        String        method,
        String        headers,
        String        body,
        String        status,
        Integer       attempts,
        LocalDateTime nextRetryAt,
        String        lastError,
        String        idempotencyKey,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.targetUrl = targetUrl;
        this.method = method;
        this.headers = headers;
        this.body = body;
        this.status = status;
        this.attempts = attempts;
        this.nextRetryAt = nextRetryAt;
        this.lastError = lastError;
        this.idempotencyKey = idempotencyKey;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public Notifications setId(Long id) {
        this.id = id;
        return this;
    }

    public String getTargetUrl() {
        return this.targetUrl;
    }

    public Notifications setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
        return this;
    }

    public String getMethod() {
        return this.method;
    }

    public Notifications setMethod(String method) {
        this.method = method;
        return this;
    }

    public String getHeaders() {
        return this.headers;
    }

    public Notifications setHeaders(String headers) {
        this.headers = headers;
        return this;
    }

    public String getBody() {
        return this.body;
    }

    public Notifications setBody(String body) {
        this.body = body;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Notifications setStatus(String status) {
        this.status = status;
        return this;
    }

    public Integer getAttempts() {
        return this.attempts;
    }

    public Notifications setAttempts(Integer attempts) {
        this.attempts = attempts;
        return this;
    }

    public LocalDateTime getNextRetryAt() {
        return this.nextRetryAt;
    }

    public Notifications setNextRetryAt(LocalDateTime nextRetryAt) {
        this.nextRetryAt = nextRetryAt;
        return this;
    }

    public String getLastError() {
        return this.lastError;
    }

    public Notifications setLastError(String lastError) {
        this.lastError = lastError;
        return this;
    }

    public String getIdempotencyKey() {
        return this.idempotencyKey;
    }

    public Notifications setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public Notifications setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public Notifications setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notifications (");

        sb.append(id);
        sb.append(", ").append(targetUrl);
        sb.append(", ").append(method);
        sb.append(", ").append(headers);
        sb.append(", ").append(body);
        sb.append(", ").append(status);
        sb.append(", ").append(attempts);
        sb.append(", ").append(nextRetryAt);
        sb.append(", ").append(lastError);
        sb.append(", ").append(idempotencyKey);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
