/*
 * This file is generated by jOOQ.
 */
package com.rc.db;


import com.rc.db.tables.FlywaySchemaHistory;
import com.rc.db.tables.Notifications;
import com.rc.db.tables.records.FlywaySchemaHistoryRecord;
import com.rc.db.tables.records.NotificationsRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<NotificationsRecord, Long> IDENTITY_NOTIFICATIONS = Identities0.IDENTITY_NOTIFICATIONS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final UniqueKey<NotificationsRecord> KEY_NOTIFICATIONS_PRIMARY = UniqueKeys0.KEY_NOTIFICATIONS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<NotificationsRecord, Long> IDENTITY_NOTIFICATIONS = Internal.createIdentity(Notifications.NOTIFICATIONS, Notifications.NOTIFICATIONS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static final UniqueKey<NotificationsRecord> KEY_NOTIFICATIONS_PRIMARY = Internal.createUniqueKey(Notifications.NOTIFICATIONS, "KEY_notifications_PRIMARY", new TableField[] { Notifications.NOTIFICATIONS.ID }, true);
    }
}
