/*
 * This file is generated by jOOQ.
 */
package com.rc.db;


import com.rc.db.tables.FlywaySchemaHistory;
import com.rc.db.tables.Notifications;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;
}
