/*
 * This file is generated by jOOQ.
 */
package com.rc.db.tables;


import com.rc.db.DefaultSchema;
import com.rc.db.Indexes;
import com.rc.db.Keys;
import com.rc.db.tables.records.NotificationsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notifications extends TableImpl<NotificationsRecord> {

    private static final long serialVersionUID = 1267552306;

    /**
     * The reference instance of <code>notifications</code>
     */
    public static final Notifications NOTIFICATIONS = new Notifications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationsRecord> getRecordType() {
        return NotificationsRecord.class;
    }

    /**
     * The column <code>notifications.id</code>.
     */
    public final TableField<NotificationsRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>notifications.target_url</code>.
     */
    public final TableField<NotificationsRecord, String> TARGET_URL = createField(DSL.name("target_url"), org.jooq.impl.SQLDataType.VARCHAR(2048).nullable(false), this, "");

    /**
     * The column <code>notifications.method</code>.
     */
    public final TableField<NotificationsRecord, String> METHOD = createField(DSL.name("method"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>notifications.headers</code>.
     */
    public final TableField<NotificationsRecord, String> HEADERS = createField(DSL.name("headers"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>notifications.body</code>.
     */
    public final TableField<NotificationsRecord, String> BODY = createField(DSL.name("body"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>notifications.status</code>.
     */
    public final TableField<NotificationsRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>notifications.attempts</code>.
     */
    public final TableField<NotificationsRecord, Integer> ATTEMPTS = createField(DSL.name("attempts"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>notifications.next_retry_at</code>.
     */
    public final TableField<NotificationsRecord, LocalDateTime> NEXT_RETRY_AT = createField(DSL.name("next_retry_at"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>notifications.last_error</code>.
     */
    public final TableField<NotificationsRecord, String> LAST_ERROR = createField(DSL.name("last_error"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>notifications.idempotency_key</code>.
     */
    public final TableField<NotificationsRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>notifications.created_at</code>.
     */
    public final TableField<NotificationsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>notifications.updated_at</code>.
     */
    public final TableField<NotificationsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>notifications</code> table reference
     */
    public Notifications() {
        this(DSL.name("notifications"), null);
    }

    /**
     * Create an aliased <code>notifications</code> table reference
     */
    public Notifications(String alias) {
        this(DSL.name(alias), NOTIFICATIONS);
    }

    /**
     * Create an aliased <code>notifications</code> table reference
     */
    public Notifications(Name alias) {
        this(alias, NOTIFICATIONS);
    }

    private Notifications(Name alias, Table<NotificationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Notifications(Name alias, Table<NotificationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Notifications(Table<O> child, ForeignKey<O, NotificationsRecord> key) {
        super(child, key, NOTIFICATIONS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.NOTIFICATIONS_IDX_NOTIFICATIONS_CREATED_AT, Indexes.NOTIFICATIONS_IDX_NOTIFICATIONS_IDEMPOTENCY_KEY, Indexes.NOTIFICATIONS_IDX_NOTIFICATIONS_STATUS_RETRY);
    }

    @Override
    public Identity<NotificationsRecord, Long> getIdentity() {
        return Keys.IDENTITY_NOTIFICATIONS;
    }

    @Override
    public UniqueKey<NotificationsRecord> getPrimaryKey() {
        return Keys.KEY_NOTIFICATIONS_PRIMARY;
    }

    @Override
    public List<UniqueKey<NotificationsRecord>> getKeys() {
        return Arrays.<UniqueKey<NotificationsRecord>>asList(Keys.KEY_NOTIFICATIONS_PRIMARY);
    }

    @Override
    public Notifications as(String alias) {
        return new Notifications(DSL.name(alias), this);
    }

    @Override
    public Notifications as(Name alias) {
        return new Notifications(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(String name) {
        return new Notifications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(Name name) {
        return new Notifications(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, Integer, LocalDateTime, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
